on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: regziv.azurecr.io
        username: ${{ secrets.acr_regziv_username }}
        password: ${{ secrets.acr_regziv_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t regziv.azurecr.io/aksziv:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push regziv.azurecr.io/aksziv:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksziv_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-ziv859e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-ziv859e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-ziv859e
        container-registry-url: regziv.azurecr.io
        container-registry-username: ${{ secrets.acr_regziv_username }}
        container-registry-password: ${{ secrets.acr_regziv_password }}
        secret-name: akszivdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-ziv859e
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          regziv.azurecr.io/aksziv:${{ github.sha }}
        imagepullsecrets: |
          akszivdockerauth
